=== santistockcode/DAM/2ºDAM/AD-0486/ProjectJAXBTeam/bin/Team.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="name" type="xs:string"/>
  <xs:element name="points" type="xs:byte"/>
  <xs:element name="player">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="points"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="team">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="player" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== santistockcode/DAM/2ºDAM/AD-0486/ProjectSAXTeam/Team.xml
<?xml version="1.0" encoding="UTF-8"?>
<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Team.xsd">
    <player>
        <name>Juan Garcia</name>
        <points>8</points>
    </player>
    <player>
        <name>Jose Lopez</name>
        <points>15</points>
    </player>
    <player>
        <name>John Smith</name>
        <points>14</points>
    </player>
    <player>
        <name>Paul King</name>
        <points>20</points>
    </player>
    <player>
        <name>Alberto Sanchez</name>
        <points>5</points>
    </player>
</team>
