=== santistockcode/DAM/2ºDAM/AD-0486/Unit-III-JAXB/src/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Author"/>
			</xs:sequence>
			<xs:attribute name="published" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="Author" type="xs:string"/>
	<xs:element name="Books">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Book" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== santistockcode/DAM/2ºDAM/AD-0486/AD_PRACTICE1.1/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Books.xsd">
    <Book published="1894">
        <Title>The Jungle Book</Title>
        <Author>Rudiard Kipling</Author>
    </Book>
    <Book published="2003">
        <Title>The Da Vinci Code</Title>
        <Author>Dan Brown</Author>
    </Book>
    <Book published="1981">
        <Title>The name of the Rose</Title>
        <Author>Umberto Eco</Author>
    </Book>
    <Book published="1605">
        <Title>Don Quixote</Title>
        <Author>Cervantes</Author>
    </Book>
</Books>
